### PR TITLE
Improved PICMI standard with additional support of:

### PR DESCRIPTION
**Pull request by hvincenti**
- Different particle/fields boundary conditions/values (fields.py),
- Guard cells (fields.py)
- Various options for the Maxwell solver,
- additional flags for IOs (diagnostics.py)
- cpu split and domain decomposition type (simulation.py)

### CODE REVIEW

**Comment by RemiLehe** [comment]
Thanks a lot for this PR!

It seems that, when merging your branch with the latest branch on Github, you maybe introduced a few unwanted changes: some of the docstrings are removed in your PR ; and some other docstrings have been formatted to Numpy style (see #1) but your PR reverts them back to the original style. Do you think you could update your PR to fix these changes? 

Thanks!

**Comment by hvincenti** [comment]
Hi Rémi,
Sure no pb I will format the added docstring to numpy style. However, it seems that not all docstrings were formatted according to this style in the master branch, do you want me to update those as well? 
Henri

**Comment by RemiLehe** [comment]
Hi Henri,
No need to format all of the docstrings to Numpy style in the current PR ; this should probably be done in a separate PR.
I clarified the docstrings that I think should be updated in this PR, through inline comments (essentially: the ones that were Numpy style already before this PR).

**Comment by hvincenti** [comment]
Hi Rémi, 

I now updated the documentation to Numpy style, let me know if you see other changes, 

Best, 

Henri

**Comment by hvincenti** [comment]
Hi Dave, 

Thanks for noticing this, I have added the requested changes in a last commit. 

Best, 

Henri

**Pull request merged**
